name: ashil_school
description: "Ashil School project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  provider: ^6.1.5
  file_picker: ^10.2.1
  image: ^4.5.4
  flutter_image_compress: ^2.4.0
  get: ^4.7.2
  lottie: ^3.3.1
  drift: ^2.28.1
  path_provider: ^2.1.5
  dio: ^5.9.0
  connectivity_plus: ^6.1.5
  sqlite3_flutter_libs: ^0.5.39
  uuid: ^4.5.1
  flutter_slidable: ^4.0.1
  share_plus: ^12.0.0
  just_audio: ^0.10.5
  record: ^6.1.2
  permission_handler: ^12.0.1
  get_storage: ^2.1.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.28.1
  build_runner: ^2.7.2
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: kufi
      fonts:
        - asset: assets/fonts/kufi.ttf
    - family: tajwal
      fonts:
        - asset: assets/fonts/ArbFONTS-Tajawal-Regular.ttf
        - asset: assets/fonts/ArbFONTS-Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/ArbFONTS-Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/ArbFONTS-Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/ArbFONTS-Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/ArbFONTS-Tajawal-Black.ttf
          weight: 900
